[package]
name = "wasm-ext"
version = "0.27.0"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>", "Tetcoin Developers <support@tetcoin.org>"]
description = "Allows passing in an external transport in a WASM environment"
license = "MIT"
edition = "2018"
keywords = ["tetcoin", "tetcore", "tetsy-libp2p", "peer-to-peer", "networking"]
categories = ["cryptography::cryptocurrencies", "network-programming", "asynchronous"]
homepage = "https://core.tetcoin.org"
repository = "https://github.com/tetcoin/tetsy-libp2p"
documentation = "https://docs.rs/wasm-ext"

[dependencies]
futures = "0.3.1"
js-sys = "0.3.19"
tetsy-libp2p-core = { version = "0.27.0", path = "../../core" }
tetsy-send-wrapper = "0.1.0"
wasm-bindgen = "0.2.42"
wasm-bindgen-futures = "0.4.4"

[features]
websocket = []
